- hosts: 127.0.0.1
  tasks:
  - name: 'Install NGINX'
    apt:
      name: nginx
      state: latest
      update_cache: true
  - name: 'Start NGINX Service'
    service:
      name: nginx
      state: started
  - name: "Printing hello world to the console"
  debug:
    msg: "Hello World"