all:
  hosts:      # this is for ungrouped machines
  children:   # this means we want our machines in groups
    west:
      hosts:  # this is for the hosts in our group
        172.31.41.16:
          ansible_user: char
    east:
      hosts:
        172.31.32.144:
    vms:
      children:
        west:
        east: