pipeline{
        agent any
        stages{
            stage('Git clone repository'){
                steps{
                    sh "git clone https://gitlab.com/qacdevops/chaperootodo_client.git"
                }
            }
            stage('Install Docker/Docker Compose'){
                steps{
                    sh "sudo usermod -aG docker $(whoami)"
                    sh "sudo apt-get update && sudo apt install curl -y"
                    sh "curl https://get.docker.com | sudo bash"
                    sh "sudo apt install -y jq"
                    sh "sudo apt-get install docker-compose-plugin"
                }
            }
            stage('Deploy Application'){
                steps{
                    sh "sudo docker-compose pull && sudo -E DB_PASSWORD=${DB_PASSWORD} docker-compose up -d"
                }
            }
        }
}