pipeline{
        agent any
        environment {
            DB_PASSWORD="password"
        }

        stages{
            stage('Git clone repository'){
                steps{
                    sh "git clone https://gitlab.com/qacdevops/chaperootodo_client.git"
                }
            }
            stage('Install Docker/Docker Compose'){
                steps{
                    sh "sudo apt-get update && sudo apt install curl -y"
                    sh "curl https://get.docker.com | sudo bash"
                    sh "chmod +x installdockercompose.sh && ./installdockercompose.sh"
                }
            }
            stage('Deploy Application'){
                steps{
                    sh "sudo docker-compose pull && sudo -E DB_PASSWORD=${DB_PASSWORD} docker-compose up -d"
                }
            }
        }
}