- hosts: all
  connection: local
  become: true
  tasks:
  - name: "Update Apt, install Prerequisites"
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: latest
      update_cache: true

  - name: "Add GPG key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present