- hosts: all
  connection: local
  become: true
  tasks:
  - name: "Update Apt, install Prerequisites"
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - apt-transport-https
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest
      update_cache: true
  - name: "Add GPG key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: "Add Docker repository"
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu
      state: present
  - name: "Update repository and install Docker"
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: latest
      update_cache: true