- hosts: all
  become: true
  vars:
    host_ip: "{{ansible_default_ipv4.address}}"
  tasks:
  - name: Copy host IP to file
    copy:
      content: "{{host_ip}}"
      dest: /home/ubuntu/public-ip.txt