- hosts: all
  become: true
  tasks:
  - name: Get IP
    shell: dig +short myip.opendns.com @resolver1.opendns.com
    register: publichostip
  - name: Create a file with the IP
    copy:
      dest: /home/ubuntu/public-ip.txt
      content: "{{publichostip}}"